### ISSUE TITLE
这个 在gulp里面怎么写  有例子吗

### ISSUE THREAD

**Issue by ghost** [yanyu0517/biz-mock#2]
这个 在gulp里面怎么写  有例子吗

**Comment by ghost** [comment]
能不能给个 gulpfile.js文件 编写模板

**Comment by yanyu0517** [comment]
还没有写gulp插件，后续会补充上~

**Comment by yanyu0517** [comment]
带mock功能server的gulp插件
[gulp-biz-server](https://github.com/yanyu0517/gulp-biz-server)
